### Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [1]:
import numpy as np


In [2]:
ipvector = np.array([1, 2, 3,4])     # input array
N=4                                  #Number of columns in the output. If N is not specified, a square array is returned (N = len(x)).where x is input array

In [3]:
matrix=np.column_stack([ipvector**(N-i-1) for i in range(N)])   #column_stack() function is used to stack 1-D arrays as columns into a 2-D array
print(matrix)


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [4]:
#np.vander(ipvector, increasing=True)

#### To make Alexandre Theophile Vandermonde matrix we need three inputs in function.
- ipvector 
- No of coulumns in output
- Order of the powers of the columns(optional). If True, the powers increase from left to right, if False (the default) they      are reversed.

In [5]:
def vander_matrix(ipvector,N,bool):
    if bool == False:
        matrix=np.column_stack([ipvector**(N-i-1) for i in range(N)])
    else:
        matrix = np.column_stack([ipvector**(i) for i in range(N)])

    return matrix
    

In [6]:
vander_matrix(ipvector,4, False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [7]:
vander_matrix(ipvector,4, True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

### Problem Statement 2: 

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


#### To Calculate Moving Averages 
* We will first calculate average of first 3 elements and that will be stored as first moving average. 
* Then window will be shifted one position to the right and again average of elements present in the window will
  be calculated and stored in the list.

In [8]:
def moving_average(arr,window_size):
    i=0
    moving_averages = []  #created empty list 
    while i < len(arr) - window_size + 1:
        window_average = round(np.sum(arr[i:i+window_size]) / window_size, 2) #calculating average of current window
        moving_averages.append(window_average)
        i += 1
    print(moving_averages)

    

In [9]:
moving_average([3,5,7,2,8,10,11,65,72,81,99,100,150],3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
